version: '3.4'
services:
  custom-upload-share:
    image: alfresco-share-custom-upload:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: custom-upload-acs
      REPO_PORT: 8080
    ports:
      - "8180:8080"
      - "9898:8888"
# Optional
#  custom-upload-acs:
#    image: alfresco/alfresco-content-repository-community:6.1.2-ga
#    environment:
#      JAVA_OPTS: "
#                -Ddb.driver=org.postgresql.Driver
#                -Ddb.username=alfresco
#                -Ddb.password=alfresco
#                -Ddb.url=jdbc:postgresql://custom-upload-postgres:5432/alfresco
#                -Dsolr.host=custom-upload-ass
#                -Dsolr.port=8983
#                -Dsolr.secureComms=none
#                -Dsolr.base.url=/solr
#                -Dindex.subsystem.name=solr6
#                -Dcsrf.filter.enabled=false
#                -Dmessaging.broker.url=\"vm://localhost?broker.persistent=false\"
#                "
#    ports:
#      - "8080:8080"
#    volumes:
#      - custom-upload-acs-volume:/usr/local/tomcat/alf_data
#    depends_on:
#      - custom-upload-postgres
#  custom-upload-postgres:
#    image: postgres:9.6
#    environment:
#      POSTGRES_DB: alfresco
#      POSTGRES_USER: alfresco
#      POSTGRES_PASSWORD: alfresco
#    command: postgres -c max_connections=300 -c log_min_messages=LOG
#    ports:
#      - "5555:5432"
#    volumes:
#      - custom-upload-db-volume:/var/lib/postgresql/data
#  custom-upload-ass:
#    image: alfresco/alfresco-search-services:1.2.0
#    environment:
#      SOLR_ALFRESCO_HOST: custom-upload-acs
#      SOLR_ALFRESCO_PORT: 8080
#      SOLR_SOLR_HOST: custom-upload-ass
#      SOLR_SOLR_PORT: 8983
#      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
#    ports:
#      - "8983:8983"
#    volumes:
#      - custom-upload-ass-volume:/opt/alfresco-search-services/contentstore
#      - custom-upload-ass-volume:/opt/alfresco-search-services/data
#volumes:
#  custom-upload-acs-volume:
#    external: true
#  custom-upload-db-volume:
#    external: true
#  custom-upload-ass-volume:
#    external: true